03. EndPoints/Terme.Endpoints.WebUI/Areas/Admin/Models/Categories/AddCategoryViewModel.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using Terme.Core.Domain.Categories.Entities;
using Terme.Core.Resources.Resources;

namespace Terme.Endpoints.WebUI.Areas.Admin.Models.Categories
{
    public class AddCategoryViewModel
    {
        [Required(ErrorMessage = SharedResource.Required)]
        [Display(Name = SharedResource.CategoryName)]
        public string Name { get; set; }
        [Display(Name = SharedResource.ParentCategory)]
        public long? ParentId { get; set; }
        [Required(ErrorMessage = SharedResource.Required)]
        [Display(Name = SharedResource.Photo)]
        public IFormFile Photo { get; set; }

        public List<Category> Categories { get; set; }

        public List<SelectListItem> GetCategoriesListItems()
        {

            var result =
            Categories.Select(c => new SelectListItem
            {
                Value = c.Id.ToString(),
                Text = c.Name
            }).ToList();
            result.Insert(0, new SelectListItem(string.Empty, string.Empty));
            return result;

        }
    }
}

03. EndPoints/Terme.Endpoints.WebUI/Areas/Admin/Models/Masters/AddMasterViewModel.cs
using Microsoft.AspNetCore.Http;
using System.ComponentModel.DataAnnotations;
using Terme.Core.Resources.Resources;

namespace Terme.Endpoints.WebUI.Areas.Admin.Models.Masters
{
    public class AddMasterViewModel
    {
        [Required(ErrorMessage = SharedResource.Required)]
        [Display(Name = SharedResource.FirstName)]
        public string FirstName { get; set; }

        [Required(ErrorMessage = SharedResource.Required)]
        [Display(Name = SharedResource.LastName)]
        public string LastName { get; set; }

        [Required(ErrorMessage = SharedResource.Required)]
        [Display(Name = SharedResource.Photo)]
        public IFormFile Photo { get; set; }

        [Required(ErrorMessage = SharedResource.Required)]
        [Display(Name = SharedResource.Description)]
        public string Description { get; set; }
        [Required(ErrorMessage = SharedResource.Required)]
        [Display(Name = SharedResource.ShortDescription)]
        public string ShortDescription { get; set; }
    }
}

03. EndPoints/Terme.Endpoints.WebUI/Models/ErrorViewModel.cs
using System;

namespace Terme.Endpoints.WebUI.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

03. EndPoints/Terme.Endpoints.WebUI/Areas/Admin/Controllers/CategoriesController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using Terme.Core.Domain.Categories.Commands;
using Terme.Core.Domain.Categories.Entities;
using Terme.Core.Domain.Categories.Queries;
using Terme.Endpoints.WebUI.Areas.Admin.Models.Categories;
using Terme.Endpoints.WebUI.FileServices;
using Terme.Framework.Commands;
using Terme.Framework.Queries;
using Terme.Framework.Resources;
using Terme.Framework.Web;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Terme.Endpoints.WebUI.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CategoriesController : BaseController
    {
        public CategoriesController(CommandDispatcher commandDispatcher, QueryDispatcher queryDispatcher, IResourceManager resourceManager) : base(commandDispatcher, queryDispatcher, resourceManager)
        {
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            var allCategory = _queryDispatcher.Dispatch<List<Category>>(new AllCategoryQuery());
            return View(allCategory);
        }

        public IActionResult AddCategory()
        {
            var model = new AddCategoryViewModel
            {
                Categories = _queryDispatcher.Dispatch<List<Category>>(new ParentCategoryQuery())
            };
            return View(model);
        }
        [HttpPost]
        public IActionResult AddCategory(AddCategoryViewModel model)
        {
            if (ModelState.IsValid)
            {

                var fileUrl = new FileSaver().Save(model.Photo);
                var result = _commandDispatcher.Dispatch(new AddCategoryCommand
                {
                    Name = model.Name,
                    ParentId = model.ParentId,
                    PhotoUrl = fileUrl
                });
                if (result.IsSuccess)
                {
                    return RedirectToAction("Index");
                }
                ModelState.AddModelError("", result.Message);
                foreach (string item in result.Errors)
                {
                    ModelState.AddModelError("", item);
                }
            }
            return View(model);
        }
    }
}

03. EndPoints/Terme.Endpoints.WebUI/Areas/Admin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Terme.Endpoints.WebUI.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class HomeController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
    }
}

03. EndPoints/Terme.Endpoints.WebUI/Areas/Admin/Controllers/MasterController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using Terme.Core.Domain.Masters.Commands;
using Terme.Core.Domain.Masters.Entities;
using Terme.Core.Domain.Masters.Queries;
using Terme.Endpoints.WebUI.Areas.Admin.Models.Masters;
using Terme.Endpoints.WebUI.FileServices;
using Terme.Framework.Commands;
using Terme.Framework.Queries;
using Terme.Framework.Resources;
using Terme.Framework.Web;

namespace Terme.Endpoints.WebUI.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class MastersController : BaseController
    {
        public MastersController(CommandDispatcher commandDispatcher, QueryDispatcher queryDispatcher, IResourceManager resourceManager) : base(commandDispatcher, queryDispatcher, resourceManager)
        {
        }

        public IActionResult Index()
        {
            var allMasters = _queryDispatcher.Dispatch<List<Master>>(new AllMasterQuery());
            return View(allMasters);
        }

        public IActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Add(AddMasterViewModel model)
        {
            if (ModelState.IsValid)
            {
                var fileUrl = new FileSaver().Save(model.Photo);
                var result = _commandDispatcher.Dispatch(new AddMasterCommand
                {
                    FirstName = model.FirstName,
                    LastName = model.LastName,
                    Description = model.Description,
                    ShortDescription = model.ShortDescription,
                    PhotoUrl = fileUrl
                });
                if (result.IsSuccess)
                {
                    return RedirectToAction("Index");
                }
                ModelState.AddModelError("", result.Message);
                foreach (string item in result.Errors)
                {
                    ModelState.AddModelError("", item);
                }
            }
            return View(model);
        }
    }
}

03. EndPoints/Terme.Endpoints.WebUI/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Diagnostics;
using Terme.Endpoints.WebUI.Models;

namespace Terme.Endpoints.WebUI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

03. EndPoints/Terme.Endpoints.WebUI/Areas/Admin/Views/Categories/AddCategory.cshtml
@inject IResourceManager _resourceManager
@model Terme.Endpoints.WebUI.Areas.Admin.Models.Categories.AddCategoryViewModel
@{
    ViewData["Title"] = _resourceManager[SharedResource.AddCategory];
}
<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header">
                <h3>
                    <i class="fa fa-save"></i>
                    @_resourceManager[SharedResource.AddCategory]
                </h3>
            </div>
            <div class="card-body">
                <form enctype="multipart/form-data" asp-controller="Categories" asp-action="AddCategory" asp-area="admin" method="post">
                    <div class="form-group">
                        <label asp-for="ParentId"></label>
                        <select class="form-control" asp-for="ParentId" asp-items="Model.GetCategoriesListItems()">
                        </select>
                    </div>
                    <div class="form-group">
                        <label asp-for="Name"></label>
                        <input type="text" class="form-control" asp-for="Name">
                        <span asp-validation-for="Name"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Photo"></label>
                        <input type="file" class="form-control" asp-for="Photo">
                        <span asp-validation-for="Photo"></span>
                    </div>
                    <button type="submit" class="btn btn-primary">@_resourceManager[SharedResource.Save]</button>
                </form>
            </div>
        </div>
    </div>
</div>

03. EndPoints/Terme.Endpoints.WebUI/Areas/Admin/Views/Categories/Index.cshtml
@model List<Terme.Core.Domain.Categories.Entities.Category>
@inject IResourceManager _resourceManager
@{
    ViewData["Title"] = _resourceManager[SharedResource.Categories];
}

<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header">
                <h3>
                    <i class="fa fa-save"></i>
                    @_resourceManager[SharedResource.Categories]
                </h3>
            </div>
            <div class="card-body">
                <ul>
                    @foreach (var item in Model)
                    {
                        <li>
                            @item.Name
                            @if (item?.Children?.Any() == true)
                            {
                                <ul>
                                    @foreach (var child in item.Children)
                                    {
                                        <li>
                                            @child.Name
                                        </li>
                                    }
                                </ul>
                            }
                        </li>
                    }
                </ul>
            </div>
        </div>
    </div>
</div>

03. EndPoints/Terme.Endpoints.WebUI/Areas/Admin/Views/Home/Index.cshtml
@inject IResourceManager _resourceManager
@{
    ViewData["Title"] = "Index";
}
@*<div class="card card">
    <div class="card-header">@_resourceManager[SharedResource.Introduction]</div>
    <div class="card-body">
        @Html.Raw(_resourceManager[SharedResource.WellcomeAdmin])
    </div>
    <div class="card-footer">@_resourceManager[SharedResource.GoodBye]</div>
</div>*@

03. EndPoints/Terme.Endpoints.WebUI/Areas/Admin/Views/Masters/Add.cshtml
@inject IResourceManager _resourceManager
@model Terme.Endpoints.WebUI.Areas.Admin.Models.Masters.AddMasterViewModel
@{
    ViewData["Title"] = _resourceManager[SharedResource.AddMaster];
}
<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header">
                <h3>
                    <i class="fa fa-save"></i>
                    @_resourceManager[SharedResource.AddMaster]
                </h3>
            </div>
            <div class="card-body">
                <form enctype="multipart/form-data" asp-controller="Masters" asp-action="Add" asp-area="admin" method="post">
                    <div class="form-group">
                        <label asp-for="FirstName"></label>
                        <input type="text" class="form-control" asp-for="FirstName">
                        <span asp-validation-for="FirstName"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="LastName"></label>
                        <input type="text" class="form-control" asp-for="LastName">
                        <span asp-validation-for="LastName"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ShortDescription"></label>
                        <input type="text" class="form-control" asp-for="ShortDescription">
                        <span asp-validation-for="ShortDescription"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Photo"></label>
                        <input type="file" class="form-control" asp-for="Photo">
                        <span asp-validation-for="Photo"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Description"></label>
                        <textarea asp-for="Description"></textarea>
                        <span asp-validation-for="FirstName"></span>
                    </div>
                    <button type="submit" class="btn btn-primary">@_resourceManager[SharedResource.Save]</button>
                </form>
            </div>
        </div>
    </div>
</div>
@section Scripts
{
    <script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
    <script>tinymce.init({selector:'textarea'});</script>
}

03. EndPoints/Terme.Endpoints.WebUI/Areas/Admin/Views/Masters/Index.cshtml
@model List<Terme.Core.Domain.Masters.Entities.Master>
@inject IResourceManager _resourceManager
@{
    ViewData["Title"] = _resourceManager[SharedResource.Masters];
}

<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header">
                <h3>
                    <i class="fa fa-save"></i>
                    @_resourceManager[SharedResource.Masters]
                </h3>
            </div>
            <div class="card-body">
                <table class="table table-bordered table-light">
                    @if (Model.Any())
                    {
                        foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    <img src="@item.Photo.Url" class="img-thumbnail" />
                                </td>
                                <td>
                                    @item.FirstName
                                </td>
                                <td>
                                    @item.LastName
                                </td>
                            </tr>
                        }
                    }
                    else
                    {
                        <tr>
                            @_resourceManager[SharedResource.NoDate]
                        </tr>
                    }
                </table>
            </div>
        </div>
    </div>
</div>

03. EndPoints/Terme.Endpoints.WebUI/Areas/Admin/Views/Shared/_Layout.cshtml
@inject IResourceManager _resourceManager
@inject IStringLocalizer<SharedResource> Localizer
<!DOCTYPE html>
<html dir="rtl">
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link href="~/lib/fontawesome-free/css/all.css" rel="stylesheet" />
    <link href="~/css/admin.css" rel="stylesheet" />
    @RenderSection("styles", false)
</head>
<body>
    <nav class="navbar navbar-expand navbar-dark bg-dark static-top">
        <a class="navbar-brand mr-1" href="index.html">@Localizer.GetString("AppName")</a>
    </nav>
    <div id="wrapper">
        <ul class="siderbar sidebar-nav">
            <li class="nav-item"><a href="#" class="nav-link"><span>asdf</span></a></li>
            <li class="nav-item"><a asp-action="Index" asp-controller="Categories" asp-area="Admin" class="nav-link"><span>@_resourceManager[SharedResource.Categories]</span></a></li>
            <li class="nav-item"><a asp-action="AddCategory" asp-controller="Categories" asp-area="Admin" class="nav-link"><span>@_resourceManager[SharedResource.AddCategory]</span></a></li>
            <li class="nav-item"><a asp-action="Index" asp-controller="Masters" asp-area="Admin" class="nav-link"><span>@_resourceManager[SharedResource.Masters]</span></a></li>
            <li class="nav-item"><a asp-action="Add" asp-controller="Masters" asp-area="Admin" class="nav-link"><span>@_resourceManager[SharedResource.AddMaster]</span></a></li>
        </ul>
        <div id="content-wrapper">
            <div class="container-fluid">
                @RenderBody()
            </div>
        </div>
    </div>



    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <script src="~/js/admin.js"></script>
    @RenderSection("Scripts", false)
</body>
</html>

03. EndPoints/Terme.Endpoints.WebUI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

03. EndPoints/Terme.Endpoints.WebUI/Views/Shared/_Layout.cshtml
@inject IResourceManager _resourceManager
<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <meta name="theme-color" content="#563d7c">

    <title>@ViewData["Title"] - ترمه</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;
        }
    </style>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <div class="collapse bg-dark" id="navbarHeader">
            <div class="container">
                <div class="row">
                    <div class="col-sm-8 col-md-7 py-4">
                    </div>
                    <div class="col-sm-4 offset-md-1 py-4">
                        <h4 class="text-white">تماس با ما</h4>
                        <ul class="list-unstyled">
                            <li><a href="#" class="text-white">ارتباط از طریق توییتر: @@oroumand</a></li>
                            <li><a href="#" class="text-white">ایمیل: ar.oroumand@@gmail.com</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="navbar navbar-dark bg-dark shadow-sm">
            <div class="container d-flex justify-content-between">
                <a href="#" class="navbar-brand d-flex align-items-center">
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="mr-2" viewBox="0 0 24 24" focusable="false"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z" /><circle cx="12" cy="13" r="4" /></svg>
                    <strong>ترمه</strong>
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </div>
    </header>

    <main role="main">

        <section class="jumbotron text-center">
            <div class="container">
                <h1> به فروشگاه ما خوش آمدید</h1>
                
                <p>
                    <a href="/Admin/Masters" class="btn btn-primary my-2">مشاهده اساتید</a>
                    <a href="#" class="btn btn-secondary my-2">مشاهده فروشگاه</a>
                </p>
            </div>
        </section>

    </main>

    <footer class="text-muted">
        <div class="container">
            <p class="float-right">
                </p>
        </div>
    </footer>
    @RenderBody()
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>